// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hejawrkknufurevtezfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlamF3cmtrbnVmdXJldnRlemZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjQyOTgsImV4cCI6MjA2NTU0MDI5OH0.LtN0IOT4wWkgZWzKQ8i_6kgs42tBe44zbClyRI77qYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);